version: 2
run:
  timeout: 5m
  skip-dirs:
    - "modules/\\(off\\).*"
    - "internal/modules/\\(off\\).*"

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
